### ISSUE TITLE
Delete this mod

### ISSUE THREAD

**Issue by RouterXdd** [JAMD150394/Erekir-Extende-Plus#1]
Steal whole mod of another people isn't very nice
just delete this mod and It will end good

**Comment by JAMD150394** [comment]
I understand your position, my intention was not to take away your credit. It was just repairing some textures because it was annoying to play with the banner (oh no) and thanks to your mod I have learned certain code things. thank you so much. Your request will be attended to. It should be said that I thought you had the mod abandoned.
